packages:
  - .
  - docs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - wasm-pack

overrides:
  tar: '>=7.5.8'
  axios: '>=1.13.5'
  lodash: '>=4.17.23'
  markdown-it: '>=14.1.1'
  ajv: '>=8.18.0'
