import { capitalizeFirstLetter } from "./string";

const ESLINT_DISABLE_COMMENT = "/* eslint-disable */";
const TS_NOCHECK_COMMENT = "// @ts-nocheck";
const DISCLAIMER_COMMENT = `// This file was automatically generated by @icp-sdk/bindgen-plugin.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.`;

export function prepareBinding(binding: string): string {
  return `${ESLINT_DISABLE_COMMENT}

${TS_NOCHECK_COMMENT}

${DISCLAIMER_COMMENT}

${binding}`;
}

export function indexBinding(serviceFileName: string): string {
  const serviceName = capitalizeFirstLetter(serviceFileName);

  // we don't want to disable typescript checks for this file
  return `${ESLINT_DISABLE_COMMENT}

${DISCLAIMER_COMMENT}

import {
  Actor,
  HttpAgent,
  type Agent,
  type HttpAgentOptions,
  type ActorConfig,
} from "@icp-sdk/core/agent";
import { type _SERVICE, idlFactory } from "./declarations/${serviceFileName}.did";
import { ${serviceName}, type ProcessErrorFn } from "./${serviceFileName}";

export interface CreateActorOptions {
  /**
   * @see {@link Agent}
   */
  agent?: Agent;
  /**
   * @see {@link HttpAgentOptions}
   */
  agentOptions?: HttpAgentOptions;
  /**
   * @see {@link ActorConfig}
   */
  actorOptions?: ActorConfig;
}

export function createActor(
  canisterId: string,
  options: CreateActorOptions = {},
  processError?: ProcessErrorFn
): ${serviceName} {
  const agent =
    options.agent || HttpAgent.createSync({ ...options.agentOptions });

  if (options.agent && options.agentOptions) {
    console.warn(
      "Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent."
    );
  }

  // Creates an actor with using the candid interface and the HttpAgent
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId,
    ...options.actorOptions,
  });

  return new ${serviceName}(actor, processError);
}
`;
}

export function envBinding(varNames: string[]): string {
  if (varNames.length === 0) {
    return "";
  }

  // we don't want to disable typescript checks for this file
  let env = `${ESLINT_DISABLE_COMMENT}\n\n${DISCLAIMER_COMMENT}\n\ninterface CanisterEnv {\n`;
  for (const varName of varNames) {
    env += `  readonly ["${varName}"]: string;\n`;
  }
  env += "}";
  return env;
}
