import { __PKG_NAME__ } from '../../constants.ts';

export const ESLINT_DISABLE_COMMENT = '/* eslint-disable */';
export const TS_NOCHECK_COMMENT = '// @ts-nocheck';
export const DISCLAIMER_COMMENT = `// This file was automatically generated by ${__PKG_NAME__}.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.`;
