name: codestyle

on:
  merge_group:
  pull_request:

env:
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Check JS Codestyle
        run: pnpm codestyle:check

      - name: Check Rust Linting
        run: cargo clippy --all-targets --all-features

      - name: Check Rust formatting
        run: cargo fmt -- --check
