name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]-beta.[0-9]+'

env:
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      is_beta: ${{ steps.is_beta.outputs.is_beta_tag }}
    environment:
      name: release
      url: https://www.npmjs.com/package/@icp-sdk/bindgen
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python
        uses: dfinity/ci-tools/actions/setup-python@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Setup Commitizen
        uses: dfinity/ci-tools/actions/setup-commitizen@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Determine if Beta Release
        id: is_beta
        uses: dfinity/ci-tools/actions/is-beta-tag@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Build NPM package
        run: pnpm build

      - name: Generate release notes
        uses: dfinity/ci-tools/actions/generate-release-notes@afeee4fbdc0683a88ec5a74ed7f59a2ce0e833ad # main

      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: |
          pnpm pack

          release_cmd="pnpm publish --verbose --access public --no-git-checks"
          if [ "${{ steps.is_beta.outputs.is_beta_tag }}" = 'true' ]; then
            release_cmd="$release_cmd --tag beta"
          fi
          $release_cmd

      - name: Create Github release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: 'icp-sdk-bindgen-${{ github.ref_name }}.tgz'
          bodyFile: 'RELEASE_NOTES.md'
          tag: '${{ github.ref_name }}'
          commit: 'main'
          prerelease: ${{ steps.is_beta.outputs.is_beta_tag == 'true' }}
          makeLatest: ${{ steps.is_beta.outputs.is_beta_tag == 'false' }}

  publish-docs:
    needs: release
    if: ${{ needs.release.outputs.is_beta == 'false' }}
    uses: ./.github/workflows/publish-docs.yml
    with:
      ref: ${{ github.ref_name }}
    secrets: inherit
